[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
shared = { workspace = true }

tokio = { version = "1.43.0", features = ["full"], optional = true }
sqlx = { version = "0.8.3", features = [
  "runtime-tokio",
  "tls-rustls",
  "postgres",
], optional = true }

[features]
db = ["tokio", "sqlx"]
