[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true }
shared = { workspace = true }

tokio = { version = "1.48.0", features = [
  "parking_lot",
  "rt-multi-thread",
  "macros",
], optional = true }
sqlx = { version = "0.8.6", features = [
  "runtime-tokio",
  "tls-rustls",
  "postgres",
], optional = true }

[features]
server = ["dioxus/server", "tokio", "sqlx"]
