[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = [
  "html",
  "document",
  "macro",
  "signals",
  "hooks",
  "asset",
  "logger",
  "launch",
  "router",
  "fullstack",
] }

api = { workspace = true }
shared = { workspace = true }

[features]
web = ["dioxus/web"]
server = ["api/server"]
